refactor: 위치권한과 건강 권한 앱 활성화할 때마다 확인
DeveloperAcademy-POSTECH/MacC-Team10-Guryongpo pull request #285
Opened 2024-04-01 12:18 UTC by yunwkgus

## 🐲 관련 이슈
close #283 

## 🏃‍♂️ 구현/변경 사항
- 위치권한과 건강권한의 상태 변화 확인 및 반영입니다.

2024-04-02 09:31 UTC, Damagucci-Juice requested changes
고생하셨는데 2부분만 수정해서 올려주세요 ~
감사함다 ~

2024-04-02 09:31 UTC, Damagucci-Juice commented on SoccerBeat/SoccerBeat/SoccerBeatApp.swift
> +    @State var noLocation: Bool
접근 제어자 private 설정해주세요~

2024-04-02 09:31 UTC, Damagucci-Juice commented on SoccerBeat/SoccerBeat/SoccerBeatApp.swift
> +                noLocation = healthInteracter.haveNoLocationAuthorization() ? true : false
3항 연산으로 보여주셨는데 `healthInteracter.haveNoHealthAuthorization()` 이 함수들 자체가 bool값을 가지고 있다면, 추가 여분으로 true, false 를 안 적어주셔도 될 거에요.
```swift
noHealth = healthInteracter.haveNoHealthAuthorization()
noLocation = healthInteracter.haveNoLocationAuthorization()
```

2024-04-02 11:30 UTC, yunwkgus commented on SoccerBeat/SoccerBeat/SoccerBeatApp.swift
> +    @State var noLocation: Bool
넵 반영하겠습니다!

2024-04-02 11:30 UTC, yunwkgus commented on SoccerBeat/SoccerBeat/SoccerBeatApp.swift
> +                noLocation = healthInteracter.haveNoLocationAuthorization() ? true : false
녜! 맞습니다!

2024-04-04 01:07 UTC, Damagucci-Juice approved these changes
수고하셨어요 ~~

2024-04-04 01:07 UTC, merged